### ISSUE TITLE
Some charts are incompatible with k8s clusters 1.16.x

### ISSUE THREAD

**Issue by weaktyper** [appuio/charts#105]
The latest version of the many of the deployments in the charts are incompatible with k8s `1.6.x` because the object type `apiVersion: apps/v1beta1` is deprecated.

Please upgrade charts to `apps/v1`

See deprecation notices:

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Thanks !

**Comment by srueg** [comment]
Thanks @weaktyper for the heads up.
We'll look into it and make the charts compatible.
