### ISSUE TITLE
k8up helm chart no longer provides the "jobType" label for k8up_jobs_failed_counter

### ISSUE THREAD

**Issue by cdchris12** [appuio/charts#286]
I can see in our testing cluster running version `1.0.4` of the k8up helm chart that we have an alert for a failing backup job which seems to be entirely missing the `jobType` label, causing our alerts to look a bit weird.

![Screen Shot 2021-04-13 at 10 25 42 AM](https://user-images.githubusercontent.com/5650531/114578603-a716dc80-9c42-11eb-88cc-cede954a22f3.png)

These are the metrics being exported by our k8up operator to Prometheus:

```
# HELP k8up_jobs_failed_counter The total number of backups that failed
# TYPE k8up_jobs_failed_counter counter
k8up_jobs_failed_counter{namespace="drupal-example-test1-master"} 3
```

It seems like this label simply isn't being exported correctly by the k8up operator, maybe?

**Comment by ccremer** [comment]
Thanks for the report.
I've allowed myself to track this bug in K8up repo itself: https://github.com/vshn/k8up/issues/421
Closing this here.
