### ISSUE TITLE
[metrics-server] Chart (and others) disappeared from repo

### ISSUE THREAD

**Issue by CVirus** [appuio/charts#321]
## Describe the bug

Good day, since yesterday `metrics-server` and any other chart in your repo (except for `k8up`) is not showing up in `helm search repo appuio` results.

It seems that that the [index.yaml ](https://charts.appuio.ch/index.yaml) contains only `k8up` and nothing else.

## To Reproduce

1. `helm repo add appuio https://charts.appuio.ch`
2. `helm repo update`
3. `helm pull appuio/metrics-server`

`Error: chart "metrics-server" matching  not found in appuio index. (try 'helm repo update'): no chart name found`

**Comment by ccremer** [comment]
Thanks for bringing this up. We also noticed it.
Somehow the CI workflow has removed all other helm releases from the index.
Meanwhile it's restored, but we're going to investigate how/why this happened.
